/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./manifesto.html",
    "./apply.html",
    "./success.html",
    "./privacy.html",
    "./**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-tint": "#c6c6cc",
        "primary-fixed": "#e2e2e8",
        "on-tertiary-container": "#827970",
        "on-secondary": "#263143",
        "on-surface-variant": "#c6c6cb",
        "on-surface": "#e5e2e2",
        "surface-container-low": "#1c1b1c",
        "on-tertiary-fixed": "#201b14",
        "tertiary-fixed-dim": "#d0c4ba",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#111c2d",
        "on-error": "#690005",
        "surface-bright": "#3a3939",
        "secondary-container": "#3e495d",
        "surface-container": "#201f20",
        "secondary-fixed": "#d8e3fb",
        "outline-variant": "#45474b",
        "on-secondary-fixed-variant": "#3c475a",
        "error-container": "#93000a",
        "outline": "#909095",
        "on-tertiary": "#362f28",
        "background": "#141314",
        "inverse-surface": "#e5e2e2",
        "primary-container": "#0a0c10",
        "secondary-fixed-dim": "#bcc7de",
        "tertiary": "#d0c4ba",
        "surface-variant": "#353435",
        "secondary": "#bcc7de",
        "on-primary": "#2f3035",
        "on-tertiary-fixed-variant": "#4d453e",
        "surface-container-highest": "#353435",
        "tertiary-fixed": "#ede0d6",
        "inverse-on-surface": "#313030",
        "surface-container-lowest": "#0e0e0e",
        "primary": "#c6c6cc",
        "on-background": "#e5e2e2",
        "on-primary-container": "#797a7f",
        "on-primary-fixed-variant": "#45474b",
        "on-secondary-container": "#aeb9d0",
        "surface-dim": "#141314",
        "surface-container-high": "#2a2a2a",
        "inverse-primary": "#5d5e63",
        "surface": "#141314",
        "primary-fixed-dim": "#c6c6cc",
        "error": "#ffb4ab",
        "tertiary-container": "#100b06",
        "on-primary-fixed": "#1a1c20"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "base": "8px",
        "section-gap": "64px",
        "container-padding": "24px",
        "stack-sm": "4px",
        "stack-md": "12px",
        "stack-lg": "24px",
        "gutter": "16px"
      },
      "fontFamily": {
        "headline-lg": ["EB Garamond", "serif"],
        "headline-lg-mobile": ["EB Garamond", "serif"],
        "display-lg": ["EB Garamond", "serif"],
        "data-mono": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "headline-md": ["EB Garamond", "serif"],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"]
      },
      "fontSize": {
        "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "500"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "500"}],
        "data-mono": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
